### ISSUE TITLE
Finish implementing Validations

### ISSUE THREAD

**Issue by ryanwinchester** [ryanwinchester/plasm#1]
Implement validations and test:

- [x] acceptance (valid & invalid)
- [x] cast (valid & invalid)
- [x] change (valid & invalid)
- [x] confirmation (valid & invalid)
- [x] count:is (valid & invalid)
- [x] count:min (valid & invalid)
- [x] count:max (valid & invalid)
- [x] exclusion (valid & invalid)
- [x] format (valid & invalid)
- [x] inclusion (valid & invalid)
- [x] length:is (valid & invalid)
- [x] length:min (valid & invalid)
- [x] length:max (valid & invalid)
- [x] number:less_than (valid & invalid)
- [x] number:greater_than (valid & invalid)
- [x] number:less_than_or_equal_to (valid & invalid)
- [x] number:greater_than_or_equal_to (valid & invalid)
- [x] number:equal_to (valid & invalid)
- [x] required (valid & invalid)
- [x] subset (valid & invalid)

**Comment by krlv** [comment]
Hi @ryanwinchester , I can help with that task

**Comment by ryanwinchester** [comment]
The **Validations** are stubbed here:
https://github.com/ryanwinchester/plasm/blob/master/src/Changeset/Validations.php

and the **Tests** are stubbed here:
https://github.com/ryanwinchester/plasm/blob/master/tests/ChangesetValidationsTest.php

For reference, the definitions of the functions that inspired the library are here:
https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_acceptance/3

**Comment by krlv** [comment]
@ryanwinchester I have a small question regarding `length` validation implementation. My plan is to use [mb_strlen](http://php.net/manual/en/function.mb-strlen.php) function to calculate length of the string. 
Unfortunately, `mbstring` is a non-default extension, to use [mb_strlen](http://php.net/manual/en/function.mb-strlen.php) function I need to add `ext-mbstring: *` to `require` section of composer.json file.
Are you ok with that?

**Comment by ryanwinchester** [comment]
@krlv yes, that is okay

**Comment by ryanwinchester** [comment]
All done! :)
